[2020-04-26 20:17:14,751] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company2 2020-04-26T20:17:07.013938+00:00 [queued]>
[2020-04-26 20:17:14,797] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.consulta_dados_company2 2020-04-26T20:17:07.013938+00:00 [queued]>
[2020-04-26 20:17:14,799] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:17:14,799] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 20:17:14,800] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:17:14,830] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): consulta_dados_company2> on 2020-04-26T20:17:07.013938+00:00
[2020-04-26 20:17:14,836] {{standard_task_runner.py:53}} INFO - Started process 2208 to run task
[2020-04-26 20:17:14,967] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.consulta_dados_company2 2020-04-26T20:17:07.013938+00:00 [running]> 030a07de9129.semantix
[2020-04-26 20:17:15,023] {{logging_mixin.py:112}} INFO - DEBUG GET: {'company': 'Cielo'}
[2020-04-26 20:17:15,039] {{logging_mixin.py:112}} INFO - 200
[2020-04-26 20:17:15,039] {{logging_mixin.py:112}} INFO - {"20190101CIELO": {"company": "Cielo", "date": "20190101", "answered": "6666", "reclamations": "6151", "response_time": "15 dias e 21 horas ", "unanswered": "113"}}
[2020-04-26 20:17:15,039] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 20:17:15,061] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui, task_id=consulta_dados_company2, execution_date=20200426T201707, start_date=20200426T201714, end_date=20200426T201715
[2020-04-26 20:17:24,702] {{logging_mixin.py:112}} INFO - [2020-04-26 20:17:24,701] {{local_task_job.py:103}} INFO - Task exited with return code 0
