[2020-04-26 20:17:14,765] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.delete_dados_company 2020-04-26T20:17:07.013938+00:00 [queued]>
[2020-04-26 20:17:14,810] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.delete_dados_company 2020-04-26T20:17:07.013938+00:00 [queued]>
[2020-04-26 20:17:14,810] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:17:14,811] {{taskinstance.py:867}} INFO - Starting attempt 1 of 2
[2020-04-26 20:17:14,811] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 20:17:14,841] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): delete_dados_company> on 2020-04-26T20:17:07.013938+00:00
[2020-04-26 20:17:14,851] {{standard_task_runner.py:53}} INFO - Started process 2210 to run task
[2020-04-26 20:17:14,983] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.delete_dados_company 2020-04-26T20:17:07.013938+00:00 [running]> 030a07de9129.semantix
[2020-04-26 20:17:15,036] {{logging_mixin.py:112}} INFO - DEBUG DELETE: {'company': 'Cielo'}
[2020-04-26 20:17:15,048] {{logging_mixin.py:112}} INFO - 200
[2020-04-26 20:17:15,049] {{logging_mixin.py:112}} INFO - "Deleted"
[2020-04-26 20:17:15,050] {{logging_mixin.py:112}} INFO - 
[2020-04-26 20:17:15,050] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 20:17:15,068] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui, task_id=delete_dados_company, execution_date=20200426T201707, start_date=20200426T201714, end_date=20200426T201715
[2020-04-26 20:17:24,706] {{logging_mixin.py:112}} INFO - [2020-04-26 20:17:24,705] {{local_task_job.py:103}} INFO - Task exited with return code 0
