[2020-04-26 19:16:28,387] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T18:56:32.539053+00:00 [queued]>
[2020-04-26 19:16:28,418] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T18:56:32.539053+00:00 [queued]>
[2020-04-26 19:16:28,418] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 19:16:28,418] {{taskinstance.py:867}} INFO - Starting attempt 2 of 2
[2020-04-26 19:16:28,419] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-04-26 19:16:28,448] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): persiste_dados_mongodb> on 2020-04-26T18:56:32.539053+00:00
[2020-04-26 19:16:28,478] {{standard_task_runner.py:53}} INFO - Started process 28904 to run task
[2020-04-26 19:16:28,568] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: ReclameAqui.persiste_dados_mongodb 2020-04-26T18:56:32.539053+00:00 [running]> 030a07de9129.semantix
[2020-04-26 19:16:28,619] {{logging_mixin.py:112}} INFO - 200
[2020-04-26 19:16:28,619] {{logging_mixin.py:112}} INFO - {"id": "20200426CIELO"}
[2020-04-26 19:16:28,620] {{python_operator.py:114}} INFO - Done. Returned value was: None
[2020-04-26 19:16:28,634] {{taskinstance.py:1048}} INFO - Marking task as SUCCESS.dag_id=ReclameAqui, task_id=persiste_dados_mongodb, execution_date=20200426T185632, start_date=20200426T191628, end_date=20200426T191628
[2020-04-26 19:16:38,386] {{logging_mixin.py:112}} INFO - [2020-04-26 19:16:38,385] {{local_task_job.py:103}} INFO - Task exited with return code 0
